import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

// import components
import Landing from '../components/Landing';
import Header from '../components/Header';
import About from '../components/About';
import Skills from '../components/Skills';
import Projects from '../components/Projects';
import Contact from '../components/Contact';

export default function Home() {
  return (
    <div>
      <Head>
        <meta charset="UTF-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>Bedant Hota</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <meta name="google-site-verification" content="APXtFO5UJJp1aRasNr_aoCYnSkC7odmuACEZRLn4X6U" />
      </Head>
      <header>
        <Header />
      </header>
      <section>
        <div>
          <Landing />
          <About />
          <Skills />
          <Projects />
          <Contact />
        </div>
      </section>
    </div>
  )
}
